// <auto-generated />
using System;
using System.Text.Json;
using Integrios.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Integrios.Migrations.Postgres.Migrations
{
    [DbContext(typeof(IntegriosDbContext))]
    [Migration("20260819161922_PostgresBaseline")]
    partial class PostgresBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Integrios.Domain.Entities.Connection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonElement>("Config")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("config")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DestinationAuthentication")
                        .HasColumnType("jsonb")
                        .HasColumnName("destination_authentication");

                    b.Property<string>("Environment")
                        .HasColumnType("text")
                        .HasColumnName("environment");

                    b.Property<Guid>("ConnectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("connector_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SourceVerification")
                        .HasColumnType("jsonb")
                        .HasColumnName("source_verification");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'active'::text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("connections_pkey");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("uq_connections_tenant_id_id");

                    b.HasAlternateKey("TenantId", "Name")
                        .HasName("uq_connections_tenant_name");

                    b.HasIndex(new[] { "TenantId" }, "idx_connections_tenant_id");

                    b.ToTable("connections", null, t =>
                        {
                            t.HasCheckConstraint("ck_connections_destination_authentication_object", "destination_authentication IS NULL OR jsonb_typeof(destination_authentication) = 'object'");

                            t.HasCheckConstraint("ck_connections_source_verification_object", "source_verification IS NULL OR jsonb_typeof(source_verification) = 'object'");
                        });
                });

            modelBuilder.Entity("Integrios.Domain.Entities.DeliveryAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("FailurePhase")
                        .HasColumnType("text")
                        .HasColumnName("failure_phase");

                    b.Property<JsonElement?>("RequestPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("request_payload");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text")
                        .HasColumnName("response_body");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_status_code");

                    b.Property<DateTimeOffset>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("SubscriptionDeliveryId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_delivery_id");

                    b.HasKey("Id")
                        .HasName("delivery_attempts_pkey");

                    b.HasAlternateKey("SubscriptionDeliveryId", "AttemptNumber")
                        .HasName("uq_delivery_attempts_delivery_number");

                    b.HasAlternateKey("SubscriptionDeliveryId", "Id")
                        .HasName("uq_delivery_attempts_delivery_id");

                    b.HasIndex(new[] { "SubscriptionDeliveryId", "AttemptNumber" }, "idx_delivery_attempts_delivery");

                    b.ToTable("delivery_attempts", null, t =>
                        {
                            t.HasCheckConstraint("ck_delivery_attempts_completion", "((status = 'in_progress' AND completed_at IS NULL) OR (status <> 'in_progress' AND completed_at IS NOT NULL))");

                            t.HasCheckConstraint("ck_delivery_attempts_failure_phase", "((status = 'failed' AND failure_phase IS NOT NULL AND failure_phase IN ('transform', 'secret_resolution', 'request_construction', 'http')) OR (status <> 'failed' AND failure_phase IS NULL))");

                            t.HasCheckConstraint("ck_delivery_attempts_number_positive", "attempt_number > 0");

                            t.HasCheckConstraint("ck_delivery_attempts_status", "status IN ('in_progress', 'succeeded', 'failed', 'indeterminate')");
                        });
                });

            modelBuilder.Entity("Integrios.Domain.Entities.SubscriptionDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("ActiveAttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_attempt_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeliverAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deliver_after");

                    b.Property<Guid>("DestinationConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_connection_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<JsonElement>("HttpExecutionSnapshot")
                        .HasColumnType("jsonb")
                        .HasColumnName("http_execution_snapshot");

                    b.Property<string>("ConnectorKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("connector_key");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<int>("LifetimeAttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("lifetime_attempt_count");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCycleAttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_cycle_attempt_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'::text");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<string>("Traceparent")
                        .HasColumnType("text")
                        .HasColumnName("traceparent");

                    b.Property<JsonElement?>("TransformConfigSnapshot")
                        .HasColumnType("jsonb")
                        .HasColumnName("transform_config_snapshot");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("subscription_deliveries_pkey");

                    b.HasAlternateKey("EventId", "SubscriptionId")
                        .HasName("uq_subscription_deliveries_event_subscription");

                    b.HasIndex(new[] { "Status", "LeaseExpiresAt", "DeliverAfter", "CreatedAt" }, "idx_subscription_deliveries_claimable")
                        .HasFilter("(status = ANY (ARRAY['pending'::text, 'in_flight'::text]))");

                    b.HasIndex(new[] { "EventId" }, "idx_subscription_deliveries_event_id");

                    b.HasIndex(new[] { "SubscriptionId" }, "idx_subscription_deliveries_subscription_id");

                    b.ToTable("subscription_deliveries", null, t =>
                        {
                            t.HasCheckConstraint("ck_subscription_deliveries_attempt_counts_nonnegative", "lifetime_attempt_count >= 0 AND retry_cycle_attempt_count >= 0 AND retry_cycle_attempt_count <= lifetime_attempt_count");

                            t.HasCheckConstraint("ck_subscription_deliveries_lease_state", "((status = 'in_flight' AND active_attempt_id IS NOT NULL AND lease_expires_at IS NOT NULL) OR (status IN ('pending', 'succeeded', 'dead_lettered') AND active_attempt_id IS NULL AND lease_expires_at IS NULL))");
                        });
                });

            modelBuilder.Entity("Integrios.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<JsonElement?>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<JsonElement>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<Guid?>("SourceConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_connection_id");

                    b.Property<string>("SourceEventId")
                        .HasColumnType("text")
                        .HasColumnName("source_event_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'accepted'::text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_id");

                    b.HasKey("Id")
                        .HasName("events_pkey");

                    b.HasIndex(new[] { "TenantId", "IdempotencyKey" }, "idx_events_idempotency")
                        .IsUnique()
                        .HasFilter("(idempotency_key IS NOT NULL)");

                    b.HasIndex(new[] { "TenantId" }, "idx_events_tenant_id");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Integrios.Domain.Entities.Connector", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ContractVersion")
                        .HasColumnType("integer")
                        .HasColumnName("contract_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direction");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Manifest")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("manifest");

                    b.Property<int>("ManifestSchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("manifest_schema_version");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'active'::text");

                    b.Property<string>("SupportedAuthSchemes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("supported_auth_schemes")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("connectors_pkey");

                    b.HasAlternateKey("Key", "ContractVersion")
                        .HasName("uq_connectors_key_contract_version");

                    b.ToTable("connectors", null, t =>
                        {
                            t.HasCheckConstraint("ck_connectors_contract_version_positive", "contract_version > 0");

                            t.HasCheckConstraint("ck_connectors_manifest_identity", "manifest->>'key' = key AND (manifest->>'contract_version')::INTEGER = contract_version AND (manifest->>'manifest_schema_version')::INTEGER = manifest_schema_version");

                            t.HasCheckConstraint("ck_connectors_manifest_object", "jsonb_typeof(manifest) = 'object'");

                            t.HasCheckConstraint("ck_connectors_manifest_schema_version_positive", "manifest_schema_version > 0");
                        });
                });

            modelBuilder.Entity("Integrios.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("DestinationConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_connection_id");

                    b.Property<string>("HttpDelivery")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("http_delivery")
                        .HasDefaultValueSql("'{\"body\": \"json\", \"method\": \"POST\", \"headers\": {}, \"version\": 1}'::jsonb");

                    b.Property<JsonElement>("MatchRules")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("match_rules")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("OrderIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("order_index");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'active'::text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_id");

                    b.Property<JsonElement?>("TransformConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("transform_config");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("routes_pkey");

                    b.HasIndex(new[] { "TopicId" }, "idx_subscriptions_topic_id");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("Integrios.Domain.Entities.OperatorKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_key");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("secret_hash");

                    b.HasKey("Id")
                        .HasName("operator_keys_pkey");

                    b.HasAlternateKey("PublicKey")
                        .HasName("operator_keys_public_key_key");

                    b.HasIndex(new[] { "PublicKey" }, "idx_operator_keys_lookup")
                        .HasFilter("(revoked_at IS NULL)");

                    b.ToTable("operator_keys", (string)null);
                });

            modelBuilder.Entity("Integrios.Domain.Entities.TenantApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_hash");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_prefix");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'active'::text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("tenant_api_keys_pkey");

                    b.HasAlternateKey("KeyPrefix")
                        .HasName("tenant_api_keys_key_prefix_key");

                    b.HasIndex(new[] { "KeyHash" }, "idx_tenant_api_keys_key_hash")
                        .IsUnique();

                    b.HasIndex(new[] { "TenantId" }, "idx_tenant_api_keys_tenant_id");

                    b.ToTable("tenant_api_keys", (string)null);
                });

            modelBuilder.Entity("Integrios.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Environment")
                        .HasColumnType("text")
                        .HasColumnName("environment");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'active'::text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("tenants_pkey");

                    b.HasAlternateKey("Slug")
                        .HasName("tenants_slug_key");

                    b.ToTable("tenants", null, t =>
                        {
                            t.HasCheckConstraint("chk_tenants_slug_dns_label", "slug ~ '^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$'");
                        });
                });

            modelBuilder.Entity("Integrios.Domain.ValueObjects.SourceEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CallbackPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("callback_path");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'active'::text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_id");

                    b.HasKey("Id")
                        .HasName("source_endpoints_pkey");

                    b.HasAlternateKey("CallbackPath")
                        .HasName("source_endpoints_callback_path_key");

                    b.HasIndex("TenantId", "TopicId", "ConnectionId")
                        .IsUnique()
                        .HasDatabaseName("uq_source_endpoints_active_association")
                        .HasFilter("(status = 'active'::text)");

                    b.HasIndex("TenantId", "TopicId", "ConnectionId", "CreatedAt")
                        .HasDatabaseName("idx_source_endpoints_association");

                    b.ToTable("source_endpoints", null, t =>
                        {
                            t.HasCheckConstraint("ck_source_endpoints_revoked_at", "((status = 'active' AND revoked_at IS NULL) OR (status = 'revoked' AND revoked_at IS NOT NULL))");

                            t.HasCheckConstraint("ck_source_endpoints_status", "status IN ('active', 'revoked')");
                        });
                });

            modelBuilder.Entity("Integrios.Domain.Entities.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'active'::text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pipelines_pkey");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("uq_topics_tenant_id_id");

                    b.HasAlternateKey("TenantId", "Name")
                        .HasName("uq_topics_tenant_name");

                    b.HasIndex(new[] { "TenantId" }, "idx_topics_tenant_id");

                    b.ToTable("topics", (string)null);
                });

            modelBuilder.Entity("Integrios.Domain.Entities.TopicSource", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_id");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("InactiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inactive_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'active'::text");

                    b.HasKey("TenantId", "TopicId", "ConnectionId")
                        .HasName("topic_sources_pkey");

                    b.HasIndex("TopicId")
                        .HasDatabaseName("idx_topic_sources_topic_id");

                    b.HasIndex(new[] { "ConnectionId" }, "idx_topic_sources_connection_id");

                    b.ToTable("topic_sources", null, t =>
                        {
                            t.HasCheckConstraint("ck_topic_sources_inactive_at", "((status = 'active' AND inactive_at IS NULL) OR (status = 'inactive' AND inactive_at IS NOT NULL))");

                            t.HasCheckConstraint("ck_topic_sources_status", "status IN ('active', 'inactive')");
                        });
                });

            modelBuilder.Entity("Integrios.Infrastructure.Outbox.OutboxEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeliverAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deliver_after");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<JsonElement>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Traceparent")
                        .HasColumnType("text")
                        .HasColumnName("traceparent");

                    b.HasKey("Id")
                        .HasName("outbox_pkey");

                    b.HasIndex(new[] { "DeliverAfter", "CreatedAt" }, "idx_outbox_pending")
                        .HasFilter("(processed_at IS NULL)");

                    NpgsqlIndexBuilderExtensions.HasNullSortOrder(b.HasIndex(new[] { "DeliverAfter", "CreatedAt" }, "idx_outbox_pending"), new[] { NullSortOrder.NullsFirst, NullSortOrder.NullsLast });

                    b.ToTable("outbox", (string)null);
                });

            modelBuilder.Entity("Integrios.Domain.Entities.Connection", b =>
                {
                    b.HasOne("Integrios.Domain.Entities.Connector", null)
                        .WithMany()
                        .HasForeignKey("ConnectorId")
                        .IsRequired()
                        .HasConstraintName("connections_connector_id_fkey");

                    b.HasOne("Integrios.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("connections_tenant_id_fkey");
                });

            modelBuilder.Entity("Integrios.Domain.Entities.DeliveryAttempt", b =>
                {
                    b.HasOne("Integrios.Domain.Entities.SubscriptionDelivery", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionDeliveryId")
                        .IsRequired()
                        .HasConstraintName("delivery_attempts_subscription_delivery_id_fkey");
                });

            modelBuilder.Entity("Integrios.Domain.Entities.SubscriptionDelivery", b =>
                {
                    b.HasOne("Integrios.Domain.Entities.Connection", null)
                        .WithMany()
                        .HasForeignKey("DestinationConnectionId")
                        .IsRequired()
                        .HasConstraintName("subscription_deliveries_destination_connection_id_fkey");

                    b.HasOne("Integrios.Domain.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("subscription_deliveries_event_id_fkey");

                    b.HasOne("Integrios.Domain.Entities.Subscription", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .IsRequired()
                        .HasConstraintName("subscription_deliveries_subscription_id_fkey");

                    b.HasOne("Integrios.Domain.Entities.DeliveryAttempt", null)
                        .WithMany()
                        .HasForeignKey("Id", "ActiveAttemptId")
                        .HasPrincipalKey("SubscriptionDeliveryId", "Id")
                        .HasConstraintName("fk_subscription_deliveries_active_attempt");
                });

            modelBuilder.Entity("Integrios.Domain.Entities.Event", b =>
                {
                    b.HasOne("Integrios.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("events_tenant_id_fkey");

                    b.HasOne("Integrios.Domain.Entities.Connection", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "SourceConnectionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .HasConstraintName("fk_events_source_connection_tenant");

                    b.HasOne("Integrios.Domain.Entities.Topic", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "TopicId")
                        .HasPrincipalKey("TenantId", "Id")
                        .HasConstraintName("fk_events_topic_tenant");

                    b.HasOne("Integrios.Domain.Entities.TopicSource", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "TopicId", "SourceConnectionId")
                        .HasConstraintName("fk_events_topic_source");
                });

            modelBuilder.Entity("Integrios.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("Integrios.Domain.Entities.Connection", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "DestinationConnectionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_destination_connection_tenant");

                    b.HasOne("Integrios.Domain.Entities.Topic", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "TopicId")
                        .HasPrincipalKey("TenantId", "Id")
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_topic_tenant");
                });

            modelBuilder.Entity("Integrios.Domain.Entities.TenantApiKey", b =>
                {
                    b.HasOne("Integrios.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("tenant_api_keys_tenant_id_fkey");
                });

            modelBuilder.Entity("Integrios.Domain.ValueObjects.SourceEndpoint", b =>
                {
                    b.HasOne("Integrios.Domain.Entities.TopicSource", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "TopicId", "ConnectionId")
                        .IsRequired()
                        .HasConstraintName("fk_source_endpoints_topic_source");
                });

            modelBuilder.Entity("Integrios.Domain.Entities.Topic", b =>
                {
                    b.HasOne("Integrios.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("pipelines_tenant_id_fkey");
                });

            modelBuilder.Entity("Integrios.Domain.Entities.TopicSource", b =>
                {
                    b.HasOne("Integrios.Domain.Entities.Connection", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ConnectionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .IsRequired()
                        .HasConstraintName("fk_topic_sources_connection_tenant");

                    b.HasOne("Integrios.Domain.Entities.Topic", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "TopicId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_topic_sources_topic_tenant");
                });

            modelBuilder.Entity("Integrios.Infrastructure.Outbox.OutboxEntry", b =>
                {
                    b.HasOne("Integrios.Domain.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("outbox_event_id_fkey");
                });
#pragma warning restore 612, 618
        }
    }
}
