// <auto-generated />
using System;
using Integrios.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Integrios.Migrations.SqlServer.Migrations
{
    [DbContext(typeof(IntegriosDbContext))]
    [Migration("20260825023301_DeleteRetiredTopicSourceAndSourceEndpoint")]
    partial class DeleteRetiredTopicSourceAndSourceEndpoint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Integrios.Domain.Entities.Connection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Config")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("config")
                        .HasDefaultValueSql("N'{}'");

                    b.Property<Guid>("ConnectorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("connector_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("DestinationAuthentication")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("destination_authentication");

                    b.Property<string>("Environment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("environment");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.Property<string>("SourceVerification")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("source_verification");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("N'active'");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id")
                        .HasName("connections_pkey");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("uq_connections_tenant_id_id");

                    b.HasAlternateKey("TenantId", "Name")
                        .HasName("uq_connections_tenant_name");

                    b.HasIndex(new[] { "TenantId" }, "idx_connections_tenant_id");

                    b.ToTable("connections", null, t =>
                        {
                            t.HasCheckConstraint("ck_connections_config_json", "ISJSON(config, VALUE) = 1");

                            t.HasCheckConstraint("ck_connections_destination_authentication_object", "destination_authentication IS NULL OR ISJSON(destination_authentication, OBJECT) = 1");

                            t.HasCheckConstraint("ck_connections_source_verification_object", "source_verification IS NULL OR ISJSON(source_verification, OBJECT) = 1");
                        });
                });

            modelBuilder.Entity("Integrios.Domain.Entities.Connector", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("ContractVersion")
                        .HasColumnType("int")
                        .HasColumnName("contract_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("direction");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("key");

                    b.Property<string>("Manifest")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("manifest");

                    b.Property<int>("ManifestSchemaVersion")
                        .HasColumnType("int")
                        .HasColumnName("manifest_schema_version");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("N'active'");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id")
                        .HasName("connectors_pkey");

                    b.HasAlternateKey("Key", "ContractVersion")
                        .HasName("uq_connectors_key_contract_version");

                    b.ToTable("connectors", null, t =>
                        {
                            t.HasCheckConstraint("ck_connectors_contract_version_positive", "contract_version > 0");

                            t.HasCheckConstraint("ck_connectors_manifest_identity", "JSON_VALUE(manifest, '$.key') = [key] AND TRY_CONVERT(int, JSON_VALUE(manifest, '$.contract_version')) = contract_version AND TRY_CONVERT(int, JSON_VALUE(manifest, '$.manifest_schema_version')) = manifest_schema_version");

                            t.HasCheckConstraint("ck_connectors_manifest_object", "ISJSON(manifest, OBJECT) = 1");

                            t.HasCheckConstraint("ck_connectors_manifest_schema_version_positive", "manifest_schema_version > 0");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Integrios.Domain.Entities.DeliveryAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int")
                        .HasColumnName("attempt_number");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_message");

                    b.Property<Guid>("EventDeliveryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_delivery_id");

                    b.Property<string>("FailurePhase")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("failure_phase");

                    b.Property<string>("RequestPayload")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("request_payload");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_body");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("int")
                        .HasColumnName("response_status_code");

                    b.Property<DateTimeOffset>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("delivery_attempts_pkey");

                    b.HasAlternateKey("EventDeliveryId", "AttemptNumber")
                        .HasName("uq_delivery_attempts_delivery_number");

                    b.HasAlternateKey("EventDeliveryId", "Id")
                        .HasName("uq_delivery_attempts_delivery_id");

                    b.HasIndex(new[] { "EventDeliveryId", "AttemptNumber" }, "idx_delivery_attempts_delivery");

                    b.ToTable("delivery_attempts", null, t =>
                        {
                            t.HasCheckConstraint("ck_delivery_attempts_completion", "((status = 'in_progress' AND completed_at IS NULL) OR (status <> 'in_progress' AND completed_at IS NOT NULL))");

                            t.HasCheckConstraint("ck_delivery_attempts_failure_phase", "((status = 'failed' AND failure_phase IS NOT NULL AND failure_phase IN ('transform', 'secret_resolution', 'request_construction', 'http')) OR (status <> 'failed' AND failure_phase IS NULL))");

                            t.HasCheckConstraint("ck_delivery_attempts_number_positive", "attempt_number > 0");

                            t.HasCheckConstraint("ck_delivery_attempts_request_payload_json", "request_payload IS NULL OR ISJSON(request_payload, VALUE) = 1");

                            t.HasCheckConstraint("ck_delivery_attempts_status", "status IN ('in_progress', 'succeeded', 'failed', 'indeterminate')");
                        });
                });

            modelBuilder.Entity("Integrios.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("accepted_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("failed_at");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metadata");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("processed_at");

                    b.Property<string>("SourceEventId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("source_event_id");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("source_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("N'accepted'");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("topic_id");

                    b.HasKey("Id")
                        .HasName("events_pkey");

                    b.HasIndex(new[] { "TenantId", "IdempotencyKey" }, "idx_events_idempotency")
                        .IsUnique()
                        .HasFilter("(idempotency_key IS NOT NULL)");

                    b.HasIndex(new[] { "TenantId" }, "idx_events_tenant_id");

                    b.ToTable("events", null, t =>
                        {
                            t.HasCheckConstraint("ck_events_metadata_json", "metadata IS NULL OR ISJSON(metadata, VALUE) = 1");

                            t.HasCheckConstraint("ck_events_payload_json", "ISJSON(payload, VALUE) = 1");

                            t.HasCheckConstraint("ck_events_source_required", "source_id IS NOT NULL");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Integrios.Domain.Entities.EventDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid?>("ActiveAttemptId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("active_attempt_id");

                    b.Property<string>("ConnectorKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("connector_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTimeOffset?>("DeliverAfter")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deliver_after");

                    b.Property<Guid>("DestinationConnectionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("destination_connection_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("failed_at");

                    b.Property<string>("HttpExecutionSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("http_execution_snapshot");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("lease_expires_at");

                    b.Property<int>("LifetimeAttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("lifetime_attempt_count");

                    b.Property<string>("MappingConfigSnapshot")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mapping_config_snapshot");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCycleAttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_cycle_attempt_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("N'pending'");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("subscription_id");

                    b.Property<string>("Traceparent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("traceparent");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id")
                        .HasName("event_deliveries_pkey");

                    b.HasAlternateKey("EventId", "SubscriptionId")
                        .HasName("uq_event_deliveries_event_subscription");

                    b.HasIndex(new[] { "Status", "LeaseExpiresAt", "DeliverAfter", "CreatedAt" }, "idx_event_deliveries_claimable")
                        .HasFilter("(status IN (N'pending', N'in_flight'))");

                    b.HasIndex(new[] { "EventId" }, "idx_event_deliveries_event_id");

                    b.HasIndex(new[] { "SubscriptionId" }, "idx_event_deliveries_subscription_id");

                    b.ToTable("event_deliveries", null, t =>
                        {
                            t.HasCheckConstraint("ck_event_deliveries_attempt_counts_nonnegative", "lifetime_attempt_count >= 0 AND retry_cycle_attempt_count >= 0 AND retry_cycle_attempt_count <= lifetime_attempt_count");

                            t.HasCheckConstraint("ck_event_deliveries_http_execution_snapshot_json", "ISJSON(http_execution_snapshot, VALUE) = 1");

                            t.HasCheckConstraint("ck_event_deliveries_lease_state", "((status = 'in_flight' AND active_attempt_id IS NOT NULL AND lease_expires_at IS NOT NULL) OR (status IN ('pending', 'succeeded', 'dead_lettered') AND active_attempt_id IS NULL AND lease_expires_at IS NULL))");

                            t.HasCheckConstraint("ck_event_deliveries_mapping_config_snapshot_json", "mapping_config_snapshot IS NULL OR ISJSON(mapping_config_snapshot, VALUE) = 1");
                        });
                });

            modelBuilder.Entity("Integrios.Domain.Entities.OperatorKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("public_key");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("revoked_at");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("secret_hash");

                    b.HasKey("Id")
                        .HasName("operator_keys_pkey");

                    b.HasAlternateKey("PublicKey")
                        .HasName("operator_keys_public_key_key");

                    b.HasIndex(new[] { "PublicKey" }, "idx_operator_keys_lookup")
                        .HasFilter("(revoked_at IS NULL)");

                    b.ToTable("operator_keys", (string)null);
                });

            modelBuilder.Entity("Integrios.Domain.Entities.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("configuration");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("connection_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("N'active'");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("topic_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id")
                        .HasName("sources_pkey");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("uq_sources_tenant_id_id");

                    b.HasIndex(new[] { "ConnectionId" }, "idx_sources_connection_id");

                    b.HasIndex(new[] { "TenantId", "CreatedAt", "Id" }, "idx_sources_tenant_created");

                    b.HasIndex(new[] { "TopicId" }, "idx_sources_topic_id");

                    b.ToTable("sources", null, t =>
                        {
                            t.HasCheckConstraint("ck_sources_configuration_json", "ISJSON(configuration, VALUE) = 1");

                            t.HasCheckConstraint("ck_sources_revoked_at", "((status = 'active' AND revoked_at IS NULL) OR (status = 'revoked' AND revoked_at IS NOT NULL))");

                            t.HasCheckConstraint("ck_sources_status", "status IN ('active', 'revoked')");

                            t.HasCheckConstraint("ck_sources_type", "type IN ('event_api', 'webhook', 'queue')");
                        });
                });

            modelBuilder.Entity("Integrios.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<Guid>("DestinationConnectionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("destination_connection_id");

                    b.Property<string>("HttpDelivery")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("http_delivery")
                        .HasDefaultValueSql("N'{\"body\": \"json\", \"method\": \"POST\", \"headers\": {}, \"version\": 1}'");

                    b.Property<string>("MappingConfig")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mapping_config");

                    b.Property<string>("MatchRules")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("match_rules")
                        .HasDefaultValueSql("N'{}'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("OrderIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("order_index");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("N'active'");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("topic_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id")
                        .HasName("routes_pkey");

                    b.HasIndex(new[] { "TopicId" }, "idx_subscriptions_topic_id");

                    b.ToTable("subscriptions", null, t =>
                        {
                            t.HasCheckConstraint("ck_subscriptions_http_delivery_json", "ISJSON(http_delivery, VALUE) = 1");

                            t.HasCheckConstraint("ck_subscriptions_mapping_config_json", "mapping_config IS NULL OR ISJSON(mapping_config, VALUE) = 1");

                            t.HasCheckConstraint("ck_subscriptions_match_rules_json", "ISJSON(match_rules, VALUE) = 1");
                        });
                });

            modelBuilder.Entity("Integrios.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Environment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("environment");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("N'active'");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id")
                        .HasName("tenants_pkey");

                    b.HasAlternateKey("Slug")
                        .HasName("tenants_slug_key");

                    b.ToTable("tenants", null, t =>
                        {
                            t.HasCheckConstraint("chk_tenants_slug_dns_label", "LEN(slug) BETWEEN 1 AND 63 AND slug NOT LIKE '%[^a-z0-9-]%' AND LEFT(slug, 1) <> '-' AND RIGHT(slug, 1) <> '-'");
                        });
                });

            modelBuilder.Entity("Integrios.Domain.Entities.TenantApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("expires_at");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("key_hash");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("key_prefix");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("N'active'");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("tenant_api_keys_pkey");

                    b.HasAlternateKey("KeyPrefix")
                        .HasName("tenant_api_keys_key_prefix_key");

                    b.HasIndex(new[] { "KeyHash" }, "idx_tenant_api_keys_key_hash")
                        .IsUnique();

                    b.HasIndex(new[] { "TenantId" }, "idx_tenant_api_keys_tenant_id");

                    b.ToTable("tenant_api_keys", (string)null);
                });

            modelBuilder.Entity("Integrios.Domain.Entities.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("N'active'");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id")
                        .HasName("pipelines_pkey");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("uq_topics_tenant_id_id");

                    b.HasAlternateKey("TenantId", "Name")
                        .HasName("uq_topics_tenant_name");

                    b.HasIndex(new[] { "TenantId" }, "idx_topics_tenant_id");

                    b.ToTable("topics", (string)null);
                });

            modelBuilder.Entity("Integrios.Infrastructure.Outbox.OutboxEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTimeOffset?>("DeliverAfter")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deliver_after");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("processed_at");

                    b.Property<string>("Traceparent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("traceparent");

                    b.HasKey("Id")
                        .HasName("outbox_pkey");

                    b.HasIndex(new[] { "DeliverAfter", "CreatedAt" }, "idx_outbox_pending")
                        .HasFilter("(processed_at IS NULL)");

                    b.ToTable("outbox", null, t =>
                        {
                            t.HasCheckConstraint("ck_outbox_payload_json", "ISJSON(payload, VALUE) = 1");
                        });
                });

            modelBuilder.Entity("Integrios.Domain.Entities.Connection", b =>
                {
                    b.HasOne("Integrios.Domain.Entities.Connector", null)
                        .WithMany()
                        .HasForeignKey("ConnectorId")
                        .IsRequired()
                        .HasConstraintName("connections_connector_id_fkey");

                    b.HasOne("Integrios.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("connections_tenant_id_fkey");
                });

            modelBuilder.Entity("Integrios.Domain.Entities.DeliveryAttempt", b =>
                {
                    b.HasOne("Integrios.Domain.Entities.EventDelivery", null)
                        .WithMany()
                        .HasForeignKey("EventDeliveryId")
                        .IsRequired()
                        .HasConstraintName("delivery_attempts_event_delivery_id_fkey");
                });

            modelBuilder.Entity("Integrios.Domain.Entities.Event", b =>
                {
                    b.HasOne("Integrios.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("events_tenant_id_fkey");

                    b.HasOne("Integrios.Domain.Entities.Source", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "SourceId")
                        .HasPrincipalKey("TenantId", "Id")
                        .HasConstraintName("fk_events_source_tenant");

                    b.HasOne("Integrios.Domain.Entities.Topic", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "TopicId")
                        .HasPrincipalKey("TenantId", "Id")
                        .HasConstraintName("fk_events_topic_tenant");
                });

            modelBuilder.Entity("Integrios.Domain.Entities.EventDelivery", b =>
                {
                    b.HasOne("Integrios.Domain.Entities.Connection", null)
                        .WithMany()
                        .HasForeignKey("DestinationConnectionId")
                        .IsRequired()
                        .HasConstraintName("event_deliveries_destination_connection_id_fkey");

                    b.HasOne("Integrios.Domain.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("event_deliveries_event_id_fkey");

                    b.HasOne("Integrios.Domain.Entities.Subscription", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .IsRequired()
                        .HasConstraintName("event_deliveries_subscription_id_fkey");

                    b.HasOne("Integrios.Domain.Entities.DeliveryAttempt", null)
                        .WithMany()
                        .HasForeignKey("Id", "ActiveAttemptId")
                        .HasPrincipalKey("EventDeliveryId", "Id")
                        .HasConstraintName("fk_event_deliveries_active_attempt");
                });

            modelBuilder.Entity("Integrios.Domain.Entities.Source", b =>
                {
                    b.HasOne("Integrios.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("fk_sources_tenant");

                    b.HasOne("Integrios.Domain.Entities.Connection", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ConnectionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .IsRequired()
                        .HasConstraintName("fk_sources_connection_tenant");

                    b.HasOne("Integrios.Domain.Entities.Topic", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "TopicId")
                        .HasPrincipalKey("TenantId", "Id")
                        .IsRequired()
                        .HasConstraintName("fk_sources_topic_tenant");
                });

            modelBuilder.Entity("Integrios.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("Integrios.Domain.Entities.Connection", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "DestinationConnectionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_destination_connection_tenant");

                    b.HasOne("Integrios.Domain.Entities.Topic", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "TopicId")
                        .HasPrincipalKey("TenantId", "Id")
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_topic_tenant");
                });

            modelBuilder.Entity("Integrios.Domain.Entities.TenantApiKey", b =>
                {
                    b.HasOne("Integrios.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("tenant_api_keys_tenant_id_fkey");
                });

            modelBuilder.Entity("Integrios.Domain.Entities.Topic", b =>
                {
                    b.HasOne("Integrios.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("pipelines_tenant_id_fkey");
                });

            modelBuilder.Entity("Integrios.Infrastructure.Outbox.OutboxEntry", b =>
                {
                    b.HasOne("Integrios.Domain.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("outbox_event_id_fkey");
                });
#pragma warning restore 612, 618
        }
    }
}
