using Integrios.Domain.Tenants;

namespace Integrios.Application.Abstractions;

public interface IAdminKeyRepository
{
    Task<AdminKey?> FindActiveByPublicKeyAsync(string publicKey, CancellationToken cancellationToken = default);

    // Bootstrap: does a live (unrevoked) global admin key already exist?
    Task<bool> HasLiveGlobalKeyAsync(CancellationToken cancellationToken = default);

    // Bootstrap: insert the first admin key row (global bootstrap key, or a tenant-scoped one)
    Task<AdminKey> InsertAsync(AdminKey adminKey, CancellationToken cancellationToken = default);

    // Rotate the live global admin key: revoke it (if any) and insert newKey in one transaction.
    // newKey.PublicKey must be freshly generated by the caller — never reuse a public_key that
    // could still collide with a prior (now-revoked) row under the UNIQUE constraint.
    Task<AdminKey> RotateGlobalAsync(AdminKey newKey, CancellationToken cancellationToken = default);
}
