using Integrios.Domain.Tenants;

namespace Integrios.Application.Abstractions;

public interface IAdminKeyRepository
{
    Task<AdminKey?> FindActiveByPublicKeyAsync(string publicKey, CancellationToken cancellationToken = default);

    // Bootstrap: does a live (unrevoked) admin key already exist?
    Task<bool> HasLiveKeyAsync(CancellationToken cancellationToken = default);

    // Bootstrap: insert the first deployment-wide admin key row.
    Task<AdminKey> InsertAsync(AdminKey adminKey, CancellationToken cancellationToken = default);

    // Rotate the live deployment-wide admin key: revoke it (if any) and insert newKey in one transaction.
    // newKey.PublicKey must be freshly generated by the caller — never reuse a public_key that
    // could still collide with a prior (now-revoked) row under the UNIQUE constraint.
    Task<AdminKey> RotateAsync(AdminKey newKey, CancellationToken cancellationToken = default);
}
